# Generated by Django 4.0.5 on 2023-05-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('idMedidor', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('idAlerta', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('fechaAlta', models.DateTimeField()),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.medidor')),
            ],
        ),
    ]
