# Generated by Django 4.0.5 on 2023-05-21 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0002_alter_medidores_user_delete_user'),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.medidores'),
        ),
        migrations.DeleteModel(
            name='Medidor',
        ),
    ]
