# Generated by Django 4.0.5 on 2023-05-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alter_alertas_medidor_delete_medidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
