# Generated by Django 4.0.5 on 2023-05-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_alter_alertas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='valor',
            field=models.FloatField(),
        ),
    ]
